
{{ config(materialized='table') }}

select 
DIMSMARTBOXBRANDID AS DIM_SMART_BOXB_RAND_ID,
SMARTBOXNATIVEID AS SMART_BOX_NATIVE_ID,
SMARTBOXCODE AS SMART_BOX_CODE,
SMARTBOXBRAND AS SMART_BOXB_RAND
from {{ source('MSSQL_DW_DBO', 'DIMSMARTBOXBRAND') }}
