
version: 2

models:
    - name: DIM_SMART_BOX_BRAND
      description: "DIM_SMART_BOX_BRAND"
      columns:
          - name: DIM_SMART_BOXB_RAND_ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: SMART_BOX_NATIVE_ID
          - name: SMART_BOX_CODE
          - name: SMART_BOXB_RAND
          
